# Generated by Django 5.0.3 on 2024-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
